car_xml = """<?xml version="1.0" encoding="UTF-8"?>
<DEXi>
  <VERSION>5.04</VERSION>
  <CREATED>2021-12-19T23:47:00</CREATED>
  <NAME>CAR_MODEL</NAME>
  <DESCRIPTION>Car demo</DESCRIPTION>
  <OPTION>Car1</OPTION>
  <OPTION>Car2</OPTION>
  <SETTINGS/>
  <ATTRIBUTE>
    <NAME>CAR</NAME>
    <DESCRIPTION>Quality of a car</DESCRIPTION>
    <SCALE>
      <SCALEVALUE>
        <NAME>unacc</NAME>
        <DESCRIPTION>unacceptable car</DESCRIPTION>
        <GROUP>BAD</GROUP>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>acc</NAME>
        <DESCRIPTION>acceptable, but I won&apos;t like it</DESCRIPTION>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>good</NAME>
        <DESCRIPTION>satisfies my needs</DESCRIPTION>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>exc</NAME>
        <DESCRIPTION>excellent car</DESCRIPTION>
        <GROUP>GOOD</GROUP>
      </SCALEVALUE>
    </SCALE>
    <FUNCTION>
      <LOW>000001230233</LOW>
    </FUNCTION>
    <OPTION>3</OPTION>
    <OPTION>2</OPTION>
    <ATTRIBUTE>
      <NAME>PRICE</NAME>
      <DESCRIPTION>Price of a car</DESCRIPTION>
      <SCALE>
        <SCALEVALUE>
          <NAME>high</NAME>
          <GROUP>BAD</GROUP>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>medium</NAME>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>low</NAME>
          <GROUP>GOOD</GROUP>
        </SCALEVALUE>
      </SCALE>
      <FUNCTION>
        <LOW>000012022</LOW>
        <ENTERED>++++++++-</ENTERED>
      </FUNCTION>
      <OPTION>2</OPTION>
      <OPTION>1</OPTION>
      <ATTRIBUTE>
        <NAME>BUY.PRICE</NAME>
        <DESCRIPTION>Buying price</DESCRIPTION>
        <SCALE>
          <SCALEVALUE>
            <NAME>high</NAME>
            <GROUP>BAD</GROUP>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>medium</NAME>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>low</NAME>
            <GROUP>GOOD</GROUP>
          </SCALEVALUE>
        </SCALE>
        <OPTION>1</OPTION>
        <OPTION>1</OPTION>
      </ATTRIBUTE>
      <ATTRIBUTE>
        <NAME>MAINT.PRICE</NAME>
        <DESCRIPTION>Maintenance price</DESCRIPTION>
        <SCALE>
          <SCALEVALUE>
            <NAME>high</NAME>
            <GROUP>BAD</GROUP>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>medium</NAME>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>low</NAME>
            <GROUP>GOOD</GROUP>
          </SCALEVALUE>
        </SCALE>
        <OPTION>2</OPTION>
        <OPTION>1</OPTION>
      </ATTRIBUTE>
    </ATTRIBUTE>
    <ATTRIBUTE>
      <NAME>TECH.CHAR.</NAME>
      <DESCRIPTION>Technical characteristics</DESCRIPTION>
      <SCALE>
        <SCALEVALUE>
          <NAME>bad</NAME>
          <GROUP>BAD</GROUP>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>acc</NAME>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>good</NAME>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>exc</NAME>
          <GROUP>GOOD</GROUP>
        </SCALEVALUE>
      </SCALE>
      <FUNCTION>
        <LOW>000012023</LOW>
      </FUNCTION>
      <OPTION>3</OPTION>
      <OPTION>2</OPTION>
      <ATTRIBUTE>
        <NAME>COMFORT</NAME>
        <DESCRIPTION>Comfort</DESCRIPTION>
        <SCALE>
          <SCALEVALUE>
            <NAME>small</NAME>
            <GROUP>BAD</GROUP>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>medium</NAME>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>high</NAME>
            <GROUP>GOOD</GROUP>
          </SCALEVALUE>
        </SCALE>
        <FUNCTION>
          <LOW>000000000000000011012012000012022022</LOW>
        </FUNCTION>
        <OPTION>2</OPTION>
        <OPTION>2</OPTION>
        <ATTRIBUTE>
          <NAME>#PERS</NAME>
          <DESCRIPTION>Maximum number of passengers</DESCRIPTION>
          <SCALE>
            <SCALEVALUE>
              <NAME>to_2</NAME>
              <GROUP>BAD</GROUP>
            </SCALEVALUE>
            <SCALEVALUE>
              <NAME>3-4</NAME>
            </SCALEVALUE>
            <SCALEVALUE>
              <NAME>more</NAME>
              <GROUP>GOOD</GROUP>
            </SCALEVALUE>
          </SCALE>
          <OPTION>2</OPTION>
          <OPTION>2</OPTION>
        </ATTRIBUTE>
        <ATTRIBUTE>
          <NAME>#DOORS</NAME>
          <DESCRIPTION>Number of doors</DESCRIPTION>
          <SCALE>
            <SCALEVALUE>
              <NAME>2</NAME>
              <GROUP>BAD</GROUP>
            </SCALEVALUE>
            <SCALEVALUE>
              <NAME>3</NAME>
            </SCALEVALUE>
            <SCALEVALUE>
              <NAME>4</NAME>
            </SCALEVALUE>
            <SCALEVALUE>
              <NAME>more</NAME>
              <GROUP>GOOD</GROUP>
            </SCALEVALUE>
          </SCALE>
          <OPTION>2</OPTION>
          <OPTION>2</OPTION>
        </ATTRIBUTE>
        <ATTRIBUTE>
          <NAME>LUGGAGE</NAME>
          <DESCRIPTION>Size of the luggage boot</DESCRIPTION>
          <SCALE>
            <SCALEVALUE>
              <NAME>small</NAME>
              <GROUP>BAD</GROUP>
            </SCALEVALUE>
            <SCALEVALUE>
              <NAME>medium</NAME>
            </SCALEVALUE>
            <SCALEVALUE>
              <NAME>big</NAME>
              <GROUP>GOOD</GROUP>
            </SCALEVALUE>
          </SCALE>
          <OPTION>2</OPTION>
          <OPTION>2</OPTION>
        </ATTRIBUTE>
      </ATTRIBUTE>
      <ATTRIBUTE>
        <NAME>SAFETY</NAME>
        <DESCRIPTION>Car&apos;s safety</DESCRIPTION>
        <SCALE>
          <SCALEVALUE>
            <NAME>small</NAME>
            <GROUP>BAD</GROUP>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>medium</NAME>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>high</NAME>
            <GROUP>GOOD</GROUP>
          </SCALEVALUE>
        </SCALE>
        <OPTION>2</OPTION>
        <OPTION>1</OPTION>
      </ATTRIBUTE>
    </ATTRIBUTE>
  </ATTRIBUTE>
</DEXi>
"""

car2_xml = """<?xml version="1.0" encoding="UTF-8"?>
<DEXi>
  <VERSION>5.04</VERSION>
  <CREATED>2021-12-15T15:49:45</CREATED>
  <OPTION>Car1</OPTION>
  <OPTION>Car2</OPTION>
  <SETTINGS/>
  <ATTRIBUTE>
    <NAME>CAR</NAME>
    <DESCRIPTION>Quality of a car</DESCRIPTION>
    <SCALE>
      <SCALEVALUE>
        <NAME>unacc</NAME>
        <DESCRIPTION>unacceptable car</DESCRIPTION>
        <GROUP>BAD</GROUP>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>acc</NAME>
        <DESCRIPTION>acceptable, but I won&apos;t like it</DESCRIPTION>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>good</NAME>
        <DESCRIPTION>satisfies my needs</DESCRIPTION>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>exc</NAME>
        <DESCRIPTION>excellent car</DESCRIPTION>
        <GROUP>GOOD</GROUP>
      </SCALEVALUE>
    </SCALE>
    <FUNCTION>
      <LOW>000001230233</LOW>
    </FUNCTION>
    <OPTION>3</OPTION>
    <OPTION>2</OPTION>
    <ATTRIBUTE>
      <NAME>PRICE</NAME>
      <DESCRIPTION>Price of a car</DESCRIPTION>
      <SCALE>
        <SCALEVALUE>
          <NAME>high</NAME>
          <GROUP>BAD</GROUP>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>medium</NAME>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>low</NAME>
          <GROUP>GOOD</GROUP>
        </SCALEVALUE>
      </SCALE>
      <FUNCTION>
        <LOW>000012022</LOW>
        <ENTERED>++++++++-</ENTERED>
      </FUNCTION>
      <OPTION>2</OPTION>
      <OPTION>1</OPTION>
      <ATTRIBUTE>
        <NAME>BUY.PRICE</NAME>
        <DESCRIPTION>Buying price</DESCRIPTION>
        <SCALE>
          <SCALEVALUE>
            <NAME>high</NAME>
            <GROUP>BAD</GROUP>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>medium</NAME>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>low</NAME>
            <GROUP>GOOD</GROUP>
          </SCALEVALUE>
        </SCALE>
        <OPTION>1</OPTION>
        <OPTION>1</OPTION>
      </ATTRIBUTE>
      <ATTRIBUTE>
        <NAME>MAINT.PRICE</NAME>
        <DESCRIPTION>Maintenance price</DESCRIPTION>
        <SCALE>
          <SCALEVALUE>
            <NAME>high</NAME>
            <GROUP>BAD</GROUP>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>medium</NAME>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>low</NAME>
            <GROUP>GOOD</GROUP>
          </SCALEVALUE>
        </SCALE>
        <OPTION>2</OPTION>
        <OPTION>1</OPTION>
      </ATTRIBUTE>
    </ATTRIBUTE>
    <ATTRIBUTE>
      <NAME>TECH.CHAR.</NAME>
      <DESCRIPTION>Technical characteristics</DESCRIPTION>
      <SCALE>
        <SCALEVALUE>
          <NAME>bad</NAME>
          <GROUP>BAD</GROUP>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>acc</NAME>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>good</NAME>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>exc</NAME>
          <GROUP>GOOD</GROUP>
        </SCALEVALUE>
      </SCALE>
      <FUNCTION>
        <LOW>000012023</LOW>
      </FUNCTION>
      <OPTION>3</OPTION>
      <OPTION>2</OPTION>
      <ATTRIBUTE>
        <NAME>COMFORT</NAME>
        <DESCRIPTION>Comfort</DESCRIPTION>
        <SCALE>
          <SCALEVALUE>
            <NAME>small</NAME>
            <GROUP>BAD</GROUP>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>medium</NAME>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>high</NAME>
            <GROUP>GOOD</GROUP>
          </SCALEVALUE>
        </SCALE>
        <FUNCTION>
          <LOW>000000000000000011012012000012022022</LOW>
        </FUNCTION>
        <OPTION>2</OPTION>
        <OPTION>2</OPTION>
        <ATTRIBUTE>
          <NAME>#PERS</NAME>
          <DESCRIPTION>Maximum number of passengers</DESCRIPTION>
          <SCALE>
            <SCALEVALUE>
              <NAME>to_2</NAME>
              <GROUP>BAD</GROUP>
            </SCALEVALUE>
            <SCALEVALUE>
              <NAME>3-4</NAME>
            </SCALEVALUE>
            <SCALEVALUE>
              <NAME>more</NAME>
              <GROUP>GOOD</GROUP>
            </SCALEVALUE>
          </SCALE>
          <OPTION>2</OPTION>
          <OPTION>2</OPTION>
        </ATTRIBUTE>
        <ATTRIBUTE>
          <NAME>#DOORS</NAME>
          <DESCRIPTION>Number of doors</DESCRIPTION>
          <SCALE>
            <SCALEVALUE>
              <NAME>2</NAME>
              <GROUP>BAD</GROUP>
            </SCALEVALUE>
            <SCALEVALUE>
              <NAME>3</NAME>
            </SCALEVALUE>
            <SCALEVALUE>
              <NAME>4</NAME>
            </SCALEVALUE>
            <SCALEVALUE>
              <NAME>more</NAME>
              <GROUP>GOOD</GROUP>
            </SCALEVALUE>
          </SCALE>
          <OPTION>2</OPTION>
          <OPTION>2</OPTION>
        </ATTRIBUTE>
        <ATTRIBUTE>
          <NAME>LUGGAGE</NAME>
          <DESCRIPTION>Size of the luggage boot</DESCRIPTION>
          <SCALE>
            <SCALEVALUE>
              <NAME>small</NAME>
              <GROUP>BAD</GROUP>
            </SCALEVALUE>
            <SCALEVALUE>
              <NAME>medium</NAME>
            </SCALEVALUE>
            <SCALEVALUE>
              <NAME>big</NAME>
              <GROUP>GOOD</GROUP>
            </SCALEVALUE>
          </SCALE>
          <OPTION>2</OPTION>
          <OPTION>2</OPTION>
        </ATTRIBUTE>
      </ATTRIBUTE>
      <ATTRIBUTE>
        <NAME>SAFETY</NAME>
        <DESCRIPTION>Car&apos;s safety</DESCRIPTION>
        <SCALE>
          <SCALEVALUE>
            <NAME>small</NAME>
            <GROUP>BAD</GROUP>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>medium</NAME>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>high</NAME>
            <GROUP>GOOD</GROUP>
          </SCALEVALUE>
        </SCALE>
        <OPTION>2</OPTION>
        <OPTION>1</OPTION>
      </ATTRIBUTE>
    </ATTRIBUTE>
  </ATTRIBUTE>
  <ATTRIBUTE>
    <NAME>CAR2</NAME>
    <DESCRIPTION>Quality of a car</DESCRIPTION>
    <SCALE>
      <SCALEVALUE>
        <NAME>unacc</NAME>
        <DESCRIPTION>unacceptable car</DESCRIPTION>
        <GROUP>BAD</GROUP>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>acc</NAME>
        <DESCRIPTION>acceptable, but I won&apos;t like it</DESCRIPTION>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>good</NAME>
        <DESCRIPTION>satisfies my needs</DESCRIPTION>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>exc</NAME>
        <DESCRIPTION>excellent car</DESCRIPTION>
        <GROUP>GOOD</GROUP>
      </SCALEVALUE>
    </SCALE>
    <FUNCTION>
      <LOW>000001230233</LOW>
    </FUNCTION>
    <OPTION>3</OPTION>
    <OPTION>2</OPTION>
    <ATTRIBUTE>
      <NAME>PRICE</NAME>
      <DESCRIPTION>Price of a car</DESCRIPTION>
      <SCALE>
        <SCALEVALUE>
          <NAME>high</NAME>
          <GROUP>BAD</GROUP>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>medium</NAME>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>low</NAME>
          <GROUP>GOOD</GROUP>
        </SCALEVALUE>
      </SCALE>
      <FUNCTION>
        <LOW>000012022</LOW>
        <ENTERED>++++++++-</ENTERED>
      </FUNCTION>
      <OPTION>2</OPTION>
      <OPTION>1</OPTION>
      <ATTRIBUTE>
        <NAME>BUY.PRICE</NAME>
        <DESCRIPTION>Buying price</DESCRIPTION>
        <SCALE>
          <SCALEVALUE>
            <NAME>high</NAME>
            <GROUP>BAD</GROUP>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>medium</NAME>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>low</NAME>
            <GROUP>GOOD</GROUP>
          </SCALEVALUE>
        </SCALE>
        <OPTION>1</OPTION>
        <OPTION>1</OPTION>
      </ATTRIBUTE>
      <ATTRIBUTE>
        <NAME>MAINT.PRICE</NAME>
        <DESCRIPTION>Maintenance price</DESCRIPTION>
        <SCALE>
          <SCALEVALUE>
            <NAME>high</NAME>
            <GROUP>BAD</GROUP>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>medium</NAME>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>low</NAME>
            <GROUP>GOOD</GROUP>
          </SCALEVALUE>
        </SCALE>
        <OPTION>2</OPTION>
        <OPTION>1</OPTION>
      </ATTRIBUTE>
    </ATTRIBUTE>
    <ATTRIBUTE>
      <NAME>TECH.CHAR.</NAME>
      <DESCRIPTION>Technical characteristics</DESCRIPTION>
      <SCALE>
        <SCALEVALUE>
          <NAME>bad</NAME>
          <GROUP>BAD</GROUP>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>acc</NAME>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>good</NAME>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>exc</NAME>
          <GROUP>GOOD</GROUP>
        </SCALEVALUE>
      </SCALE>
      <OPTION>3</OPTION>
      <OPTION>2</OPTION>
    </ATTRIBUTE>
  </ATTRIBUTE>
</DEXi>
"""

linked_xml = """<?xml version="1.0" encoding="UTF-8"?>
<DEXi>
  <VERSION>5.04</VERSION>
  <CREATED>2020-05-10T18:16:13</CREATED>
  <OPTION>1</OPTION>
  <OPTION>2</OPTION>
  <OPTION>3</OPTION>
  <OPTION>4</OPTION>
  <OPTION>5</OPTION>
  <OPTION>6</OPTION>
  <OPTION>7</OPTION>
  <OPTION>8</OPTION>
  <OPTION>9</OPTION>
  <SETTINGS>
    <LINKING>True</LINKING>
  </SETTINGS>
  <ATTRIBUTE>
    <NAME>LinkedBoundsTest</NAME>
    <SCALE>
      <SCALEVALUE>
        <NAME>L</NAME>
        <GROUP>BAD</GROUP>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>M</NAME>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>H</NAME>
        <GROUP>GOOD</GROUP>
      </SCALEVALUE>
    </SCALE>
    <FUNCTION>
      <LOW>001011112011111112011112122</LOW>
      <WEIGHTS>20;30;40</WEIGHTS>
      <LOCWEIGHTS>20.00;40.00;40.00</LOCWEIGHTS>
      <NORMLOCWEIGHTS>20.00;40.00;40.00</NORMLOCWEIGHTS>
    </FUNCTION>
    <OPTION>0</OPTION>
    <OPTION>0</OPTION>
    <OPTION>1</OPTION>
    <OPTION>0</OPTION>
    <OPTION>1</OPTION>
    <OPTION>1</OPTION>
    <OPTION>1</OPTION>
    <OPTION>1</OPTION>
    <OPTION>2</OPTION>
    <ATTRIBUTE>
      <NAME>MIN</NAME>
      <SCALE>
        <SCALEVALUE>
          <NAME>L</NAME>
          <GROUP>BAD</GROUP>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>M</NAME>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>H</NAME>
          <GROUP>GOOD</GROUP>
        </SCALEVALUE>
      </SCALE>
      <FUNCTION>
        <LOW>000011012</LOW>
      </FUNCTION>
      <OPTION>0</OPTION>
      <OPTION>0</OPTION>
      <OPTION>0</OPTION>
      <OPTION>0</OPTION>
      <OPTION>1</OPTION>
      <OPTION>1</OPTION>
      <OPTION>0</OPTION>
      <OPTION>1</OPTION>
      <OPTION>2</OPTION>
      <ATTRIBUTE>
        <NAME>A</NAME>
        <SCALE>
          <SCALEVALUE>
            <NAME>L</NAME>
            <GROUP>BAD</GROUP>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>M</NAME>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>H</NAME>
            <GROUP>GOOD</GROUP>
          </SCALEVALUE>
        </SCALE>
        <OPTION>0</OPTION>
        <OPTION>0</OPTION>
        <OPTION>0</OPTION>
        <OPTION>1</OPTION>
        <OPTION>1</OPTION>
        <OPTION>1</OPTION>
        <OPTION>2</OPTION>
        <OPTION>2</OPTION>
        <OPTION>2</OPTION>
      </ATTRIBUTE>
      <ATTRIBUTE>
        <NAME>B</NAME>
        <SCALE>
          <SCALEVALUE>
            <NAME>L</NAME>
            <GROUP>BAD</GROUP>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>M</NAME>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>H</NAME>
            <GROUP>GOOD</GROUP>
          </SCALEVALUE>
        </SCALE>
        <OPTION>0</OPTION>
        <OPTION>1</OPTION>
        <OPTION>2</OPTION>
        <OPTION>0</OPTION>
        <OPTION>1</OPTION>
        <OPTION>2</OPTION>
        <OPTION>0</OPTION>
        <OPTION>1</OPTION>
        <OPTION>2</OPTION>
      </ATTRIBUTE>
    </ATTRIBUTE>
    <ATTRIBUTE>
      <NAME>MAX</NAME>
      <SCALE>
        <SCALEVALUE>
          <NAME>L</NAME>
          <GROUP>BAD</GROUP>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>M</NAME>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>H</NAME>
          <GROUP>GOOD</GROUP>
        </SCALEVALUE>
      </SCALE>
      <FUNCTION>
        <LOW>012112222</LOW>
      </FUNCTION>
      <OPTION>0</OPTION>
      <OPTION>1</OPTION>
      <OPTION>2</OPTION>
      <OPTION>1</OPTION>
      <OPTION>1</OPTION>
      <OPTION>2</OPTION>
      <OPTION>2</OPTION>
      <OPTION>2</OPTION>
      <OPTION>2</OPTION>
      <ATTRIBUTE>
        <NAME>A</NAME>
        <SCALE>
          <SCALEVALUE>
            <NAME>L</NAME>
            <GROUP>BAD</GROUP>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>M</NAME>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>H</NAME>
            <GROUP>GOOD</GROUP>
          </SCALEVALUE>
        </SCALE>
        <OPTION>0</OPTION>
        <OPTION>0</OPTION>
        <OPTION>0</OPTION>
        <OPTION>1</OPTION>
        <OPTION>1</OPTION>
        <OPTION>1</OPTION>
        <OPTION>2</OPTION>
        <OPTION>2</OPTION>
        <OPTION>2</OPTION>
      </ATTRIBUTE>
      <ATTRIBUTE>
        <NAME>B</NAME>
        <SCALE>
          <SCALEVALUE>
            <NAME>L</NAME>
            <GROUP>BAD</GROUP>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>M</NAME>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>H</NAME>
            <GROUP>GOOD</GROUP>
          </SCALEVALUE>
        </SCALE>
        <OPTION>0</OPTION>
        <OPTION>1</OPTION>
        <OPTION>2</OPTION>
        <OPTION>0</OPTION>
        <OPTION>1</OPTION>
        <OPTION>2</OPTION>
        <OPTION>0</OPTION>
        <OPTION>1</OPTION>
        <OPTION>2</OPTION>
      </ATTRIBUTE>
    </ATTRIBUTE>
    <ATTRIBUTE>
      <NAME>MID</NAME>
      <SCALE>
        <SCALEVALUE>
          <NAME>L</NAME>
          <GROUP>BAD</GROUP>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>M</NAME>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>H</NAME>
          <GROUP>GOOD</GROUP>
        </SCALEVALUE>
      </SCALE>
      <FUNCTION>
        <LOW>001011112</LOW>
      </FUNCTION>
      <OPTION>0</OPTION>
      <OPTION>0</OPTION>
      <OPTION>1</OPTION>
      <OPTION>0</OPTION>
      <OPTION>1</OPTION>
      <OPTION>1</OPTION>
      <OPTION>1</OPTION>
      <OPTION>1</OPTION>
      <OPTION>2</OPTION>
      <ATTRIBUTE>
        <NAME>A</NAME>
        <SCALE>
          <SCALEVALUE>
            <NAME>L</NAME>
            <GROUP>BAD</GROUP>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>M</NAME>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>H</NAME>
            <GROUP>GOOD</GROUP>
          </SCALEVALUE>
        </SCALE>
        <OPTION>0</OPTION>
        <OPTION>0</OPTION>
        <OPTION>0</OPTION>
        <OPTION>1</OPTION>
        <OPTION>1</OPTION>
        <OPTION>1</OPTION>
        <OPTION>2</OPTION>
        <OPTION>2</OPTION>
        <OPTION>2</OPTION>
      </ATTRIBUTE>
      <ATTRIBUTE>
        <NAME>B</NAME>
        <SCALE>
          <SCALEVALUE>
            <NAME>L</NAME>
            <GROUP>BAD</GROUP>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>M</NAME>
          </SCALEVALUE>
          <SCALEVALUE>
            <NAME>H</NAME>
            <GROUP>GOOD</GROUP>
          </SCALEVALUE>
        </SCALE>
        <OPTION>0</OPTION>
        <OPTION>1</OPTION>
        <OPTION>2</OPTION>
        <OPTION>0</OPTION>
        <OPTION>1</OPTION>
        <OPTION>2</OPTION>
        <OPTION>0</OPTION>
        <OPTION>1</OPTION>
        <OPTION>2</OPTION>
      </ATTRIBUTE>
    </ATTRIBUTE>
  </ATTRIBUTE>
</DEXi>
"""

continuous_old_xml = """<?xml version="1.0" encoding="UTF-8"?>
<DEXi>
 <VERSION>1.0</VERSION>
 <CREATED>2021-03-11T18:32:15</CREATED>
 <LIBRARY>DEXi Library V1.0</LIBRARY>
 <FORMAT>DexiLibrary</FORMAT>
 <OPTION>Null/Null</OPTION>
 <OPTION>Null/All</OPTION>
 <OPTION>Test1</OPTION>
 <OPTION>Test2</OPTION>
 <OPTION>Test3</OPTION>
 <OPTION>Test4</OPTION>
 <OPTION>Test5</OPTION>
 <OPTION>Test6</OPTION>
 <OPTION>Test7</OPTION>
 <SETTINGS/>
 <ATTRIBUTE>
  <NAME>OneLevel</NAME>
  <SCALE>
   <SCALEVALUE>
    <NAME>0</NAME>
    <GROUP>BAD</GROUP>
   </SCALEVALUE>
   <SCALEVALUE>
    <NAME>1</NAME>
   </SCALEVALUE>
   <SCALEVALUE>
    <NAME>2</NAME>
    <GROUP>GOOD</GROUP>
   </SCALEVALUE>
  </SCALE>
  <FUNCTION>
   <LOW>012122</LOW>
  </FUNCTION>
  <OPTION/>
  <OPTION>*</OPTION>
  <OPTION>0</OPTION>
  <OPTION>1</OPTION>
  <OPTION>2</OPTION>
  <OPTION>1</OPTION>
  <OPTION>2</OPTION>
  <OPTION>2</OPTION>
  <OPTION>1</OPTION>
  <ATTRIBUTE>
   <NAME>X1</NAME>
   <SCALE>
    <SCALEVALUE>
     <NAME>0</NAME>
     <GROUP>BAD</GROUP>
    </SCALEVALUE>
    <SCALEVALUE>
     <NAME>1</NAME>
     <GROUP>GOOD</GROUP>
    </SCALEVALUE>
   </SCALE>
   <DISCRETIZE>
    <VALUE>0</VALUE>
    <BOUND Associate="Down">0</BOUND>
    <VALUE>1</VALUE>
   </DISCRETIZE>
   <OPTION/>
   <OPTION>*</OPTION>
   <OPTION>0</OPTION>
   <OPTION>0</OPTION>
   <OPTION>0</OPTION>
   <OPTION>1</OPTION>
   <OPTION>1</OPTION>
   <OPTION>1</OPTION>
   <OPTION>0</OPTION>
   <ATTRIBUTE>
    <NAME>N1</NAME>
    <SCALE>
     <CONTINUOUS>
       <LOW>-1</LOW>
       <HIGH>1</HIGH>
     </CONTINUOUS>
    </SCALE>
    <OPTION/>
    <OPTION/>
    <ALTERNATIVE>-2</ALTERNATIVE>
    <ALTERNATIVE>-2</ALTERNATIVE>
    <ALTERNATIVE>-2</ALTERNATIVE>
    <ALTERNATIVE>2</ALTERNATIVE>
    <ALTERNATIVE>2</ALTERNATIVE>
    <ALTERNATIVE>2</ALTERNATIVE>
    <ALTERNATIVE>0</ALTERNATIVE>
   </ATTRIBUTE>
  </ATTRIBUTE>
  <ATTRIBUTE>
   <NAME>X2</NAME>
   <SCALE>
    <SCALEVALUE>
     <NAME>0</NAME>
     <GROUP>BAD</GROUP>
    </SCALEVALUE>
    <SCALEVALUE>
     <NAME>1</NAME>
    </SCALEVALUE>
    <SCALEVALUE>
     <NAME>2</NAME>
     <GROUP>GOOD</GROUP>
    </SCALEVALUE>
   </SCALE>
   <DISCRETIZE>
    <VALUE>0</VALUE>
    <BOUND Associate="Up">-1</BOUND>
    <VALUE>1</VALUE>
    <BOUND Associate="Down">1</BOUND>
    <VALUE>2</VALUE>
   </DISCRETIZE>
   <OPTION/>
   <OPTION>*</OPTION>
   <OPTION>0</OPTION>
   <OPTION>1</OPTION>
   <OPTION>2</OPTION>
   <OPTION>0</OPTION>
   <OPTION>1</OPTION>
   <OPTION>2</OPTION>
   <OPTION>1</OPTION>
   <ATTRIBUTE>
    <NAME>N2</NAME>
    <SCALE>
     <CONTINUOUS/>
    </SCALE>
    <OPTION/>
    <OPTION/>
    <ALTERNATIVE>-2</ALTERNATIVE>
    <ALTERNATIVE>0</ALTERNATIVE>
    <ALTERNATIVE>2</ALTERNATIVE>
    <ALTERNATIVE>-2</ALTERNATIVE>
    <ALTERNATIVE>0</ALTERNATIVE>
    <ALTERNATIVE>2</ALTERNATIVE>
    <ALTERNATIVE>0</ALTERNATIVE>
   </ATTRIBUTE>
  </ATTRIBUTE>
 </ATTRIBUTE>
</DEXi>
"""

continuous_new_xml = """<?xml version="1.0" encoding="UTF-8"?>
<DEXi>
 <VERSION>1.0</VERSION>
 <CREATED>2021-03-11T18:32:15</CREATED>
 <LIBRARY>DEXi Library V1.0</LIBRARY>
 <FORMAT>DexiLibrary</FORMAT>
 <ALTERNATIVE>
  <NAME>Null/Null</NAME>
 </ALTERNATIVE>
 <ALTERNATIVE>
  <NAME>Null/All</NAME>
 </ALTERNATIVE>
 <ALTERNATIVE>
  <NAME>Test1</NAME>
 </ALTERNATIVE>
 <ALTERNATIVE>
  <NAME>Test2</NAME>
 </ALTERNATIVE>
 <ALTERNATIVE>
  <NAME>Test3</NAME>
 </ALTERNATIVE>
 <ALTERNATIVE>
  <NAME>Test4</NAME>
 </ALTERNATIVE>
 <ALTERNATIVE>
  <NAME>Test5</NAME>
 </ALTERNATIVE>
 <ALTERNATIVE>
  <NAME>Test6</NAME>
 </ALTERNATIVE>
 <ALTERNATIVE>
  <NAME>Test7</NAME>
 </ALTERNATIVE>
 <SETTINGS/>
 <ATTRIBUTE>
  <NAME>OneLevel</NAME>
  <SCALE>
   <SCALEVALUE>
    <NAME>0</NAME>
    <GROUP>BAD</GROUP>
   </SCALEVALUE>
   <SCALEVALUE>
    <NAME>1</NAME>
   </SCALEVALUE>
   <SCALEVALUE>
    <NAME>2</NAME>
    <GROUP>GOOD</GROUP>
   </SCALEVALUE>
  </SCALE>
  <TABLE>
   <RULE Args="0;0">0</RULE>
   <RULE Args="0;1">0:1</RULE>
   <RULE Args="0;2">2</RULE>
   <RULE Args="1;0">1:2</RULE>
   <RULE Args="1;1">2</RULE>
   <RULE Args="1;2">2</RULE>
  </TABLE>
  <ALTERNATIVE>undef</ALTERNATIVE>
  <ALTERNATIVE>0:2</ALTERNATIVE>
  <ALTERNATIVE>0</ALTERNATIVE>
  <ALTERNATIVE>1</ALTERNATIVE>
  <ALTERNATIVE>2</ALTERNATIVE>
  <ALTERNATIVE>1</ALTERNATIVE>
  <ALTERNATIVE>2</ALTERNATIVE>
  <ALTERNATIVE>2</ALTERNATIVE>
  <ALTERNATIVE>1</ALTERNATIVE>
  <ATTRIBUTE>
   <NAME>X1</NAME>
   <SCALE>
    <SCALEVALUE>
     <NAME>0</NAME>
     <GROUP>BAD</GROUP>
    </SCALEVALUE>
    <SCALEVALUE>
     <NAME>1</NAME>
     <GROUP>GOOD</GROUP>
    </SCALEVALUE>
   </SCALE>
   <DISCRETIZE>
    <VALUE>0</VALUE>
    <BOUND Associate="Down">0</BOUND>
    <VALUE>1</VALUE>
   </DISCRETIZE>
   <ALTERNATIVE>undef</ALTERNATIVE>
   <ALTERNATIVE>{0;1}</ALTERNATIVE>
   <ALTERNATIVE>0</ALTERNATIVE>
   <ALTERNATIVE>0</ALTERNATIVE>
   <ALTERNATIVE>0</ALTERNATIVE>
   <ALTERNATIVE>1</ALTERNATIVE>
   <ALTERNATIVE>1</ALTERNATIVE>
   <ALTERNATIVE>1</ALTERNATIVE>
   <ALTERNATIVE>0</ALTERNATIVE>
   <ATTRIBUTE>
    <NAME>N1</NAME>
    <SCALE>
     <CONTINUOUS/>
    </SCALE>
    <ALTERNATIVE>undef</ALTERNATIVE>
    <ALTERNATIVE>undef</ALTERNATIVE>
    <ALTERNATIVE>-2</ALTERNATIVE>
    <ALTERNATIVE>-2</ALTERNATIVE>
    <ALTERNATIVE>-2</ALTERNATIVE>
    <ALTERNATIVE>2</ALTERNATIVE>
    <ALTERNATIVE>2</ALTERNATIVE>
    <ALTERNATIVE>2</ALTERNATIVE>
    <ALTERNATIVE>0</ALTERNATIVE>
   </ATTRIBUTE>
  </ATTRIBUTE>
  <ATTRIBUTE>
   <NAME>X2</NAME>
   <SCALE>
    <SCALEVALUE>
     <NAME>0</NAME>
     <GROUP>BAD</GROUP>
    </SCALEVALUE>
    <SCALEVALUE>
     <NAME>1</NAME>
    </SCALEVALUE>
    <SCALEVALUE>
     <NAME>2</NAME>
     <GROUP>GOOD</GROUP>
    </SCALEVALUE>
   </SCALE>
   <DISCRETIZE>
    <VALUE>0</VALUE>
    <BOUND Associate="Up">-1</BOUND>
    <VALUE>1</VALUE>
    <BOUND Associate="Down">1</BOUND>
    <VALUE>2</VALUE>
   </DISCRETIZE>
   <ALTERNATIVE>undef</ALTERNATIVE>
   <ALTERNATIVE>{0;1;2}</ALTERNATIVE>
   <ALTERNATIVE>0</ALTERNATIVE>
   <ALTERNATIVE>1</ALTERNATIVE>
   <ALTERNATIVE>2</ALTERNATIVE>
   <ALTERNATIVE>0</ALTERNATIVE>
   <ALTERNATIVE>1</ALTERNATIVE>
   <ALTERNATIVE>2</ALTERNATIVE>
   <ALTERNATIVE>1</ALTERNATIVE>
   <ATTRIBUTE>
    <NAME>N2</NAME>
    <SCALE>
     <CONTINUOUS/>
    </SCALE>
    <ALTERNATIVE>undef</ALTERNATIVE>
    <ALTERNATIVE>undef</ALTERNATIVE>
    <ALTERNATIVE>-2</ALTERNATIVE>
    <ALTERNATIVE>0</ALTERNATIVE>
    <ALTERNATIVE>2</ALTERNATIVE>
    <ALTERNATIVE>-2</ALTERNATIVE>
    <ALTERNATIVE>0</ALTERNATIVE>
    <ALTERNATIVE>2</ALTERNATIVE>
    <ALTERNATIVE>0</ALTERNATIVE>
   </ATTRIBUTE>
  </ATTRIBUTE>
 </ATTRIBUTE>
</DEXi>
"""

continuous_new_no_alt_xml = """<?xml version="1.0" encoding="UTF-8"?>
<DEXi>
 <VERSION>1.0</VERSION>
 <CREATED>2021-03-11T18:32:15</CREATED>
 <LIBRARY>DEXi Library V1.0</LIBRARY>
 <FORMAT>DexiLibrary</FORMAT>
 <SETTINGS/>
 <ATTRIBUTE>
  <NAME>OneLevel</NAME>
  <SCALE>
   <SCALEVALUE>
    <NAME>0</NAME>
    <GROUP>BAD</GROUP>
   </SCALEVALUE>
   <SCALEVALUE>
    <NAME>1</NAME>
   </SCALEVALUE>
   <SCALEVALUE>
    <NAME>2</NAME>
    <GROUP>GOOD</GROUP>
   </SCALEVALUE>
  </SCALE>
  <TABLE>
   <RULE Args="0;0">0</RULE>
   <RULE Args="0;1">0:1</RULE>
   <RULE Args="0;2">2</RULE>
   <RULE Args="1;0">1:2</RULE>
   <RULE Args="1;1">2</RULE>
   <RULE Args="1;2">2</RULE>
  </TABLE>
  <ATTRIBUTE>
   <NAME>X1</NAME>
   <SCALE>
    <SCALEVALUE>
     <NAME>0</NAME>
     <GROUP>BAD</GROUP>
    </SCALEVALUE>
    <SCALEVALUE>
     <NAME>1</NAME>
     <GROUP>GOOD</GROUP>
    </SCALEVALUE>
   </SCALE>
   <DISCRETIZE>
    <VALUE>0</VALUE>
    <BOUND Associate="Down">0</BOUND>
    <VALUE>1</VALUE>
   </DISCRETIZE>
   <ATTRIBUTE>
    <NAME>N1</NAME>
    <SCALE>
     <CONTINUOUS/>
    </SCALE>
   </ATTRIBUTE>
  </ATTRIBUTE>
  <ATTRIBUTE>
   <NAME>X2</NAME>
   <SCALE>
    <SCALEVALUE>
     <NAME>0</NAME>
     <GROUP>BAD</GROUP>
    </SCALEVALUE>
    <SCALEVALUE>
     <NAME>1</NAME>
    </SCALEVALUE>
    <SCALEVALUE>
     <NAME>2</NAME>
     <GROUP>GOOD</GROUP>
    </SCALEVALUE>
   </SCALE>
   <DISCRETIZE>
    <VALUE>0</VALUE>
    <BOUND Associate="Up">-1</BOUND>
    <VALUE>1</VALUE>
    <BOUND Associate="Down">1</BOUND>
    <VALUE>2</VALUE>
   </DISCRETIZE>
   <ATTRIBUTE>
    <NAME>N2</NAME>
    <SCALE>
     <CONTINUOUS/>
    </SCALE>
   </ATTRIBUTE>
  </ATTRIBUTE>
 </ATTRIBUTE>
</DEXi>
"""

dozen_xml = """<?xml version="1.0" encoding="UTF-8"?>
<DEXi>
  <VERSION>5.04</VERSION>
  <CREATED>2022-01-27T08:34:04</CREATED>
  <OPTION>B</OPTION>
  <OPTION>B</OPTION>
  <OPTION>C</OPTION>
  <SETTINGS/>
  <ATTRIBUTE>
    <NAME>Dozen</NAME>
    <DESCRIPTION>An attribute with dozen values</DESCRIPTION>
    <SCALE>
      <SCALEVALUE>
        <NAME>v1</NAME>
        <GROUP>BAD</GROUP>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>v2</NAME>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>v3</NAME>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>v4</NAME>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>v5</NAME>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>v6</NAME>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>v7</NAME>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>v8</NAME>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>v9</NAME>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>va</NAME>
      </SCALEVALUE>
      <SCALEVALUE>
        <NAME>vb</NAME>
        <GROUP>GOOD</GROUP>
      </SCALEVALUE>
    </SCALE>
    <FUNCTION>
      <LOW>012323354567789:</LOW>
    </FUNCTION>
    <OPTION>357:</OPTION>
    <OPTION>4567</OPTION>
    <OPTION>789:</OPTION>
    <ATTRIBUTE>
      <NAME>A</NAME>
      <SCALE>
        <SCALEVALUE>
          <NAME>low</NAME>
          <GROUP>BAD</GROUP>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>med</NAME>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>high</NAME>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>vhigh</NAME>
          <GROUP>GOOD</GROUP>
        </SCALEVALUE>
      </SCALE>
      <OPTION/>
      <OPTION>2</OPTION>
      <OPTION>3</OPTION>
    </ATTRIBUTE>
    <ATTRIBUTE>
      <NAME>B</NAME>
      <SCALE>
        <SCALEVALUE>
          <NAME>low</NAME>
          <GROUP>BAD</GROUP>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>med</NAME>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>high</NAME>
        </SCALEVALUE>
        <SCALEVALUE>
          <NAME>vhigh</NAME>
          <GROUP>GOOD</GROUP>
        </SCALEVALUE>
      </SCALE>
      <OPTION>3</OPTION>
      <OPTION/>
      <OPTION/>
    </ATTRIBUTE>
  </ATTRIBUTE>
</DEXi>
"""
